added getopts

diff --git a/scriptbits b/scriptbits
--- a/scriptbits
+++ b/scriptbits
@@ -127,6 +127,24 @@ fi
 "
 }
 
+func_getopts() {
+    cat<<EOG
+# --------------------------------------------
+# Parse options
+# --------------------------------------------
+while getopts ":m:dqh" opt; do
+    case \$opt in
+        m) MOD="\$OPTARG" ;;
+        d) DEBUG=1 ;;
+        q) QUIET=1 ;;
+        h) show_help ;;
+        \\?) echo "Invalid option: -\$OPTARG" >&2; show_help ;;
+        :) echo "Option -\$OPTARG requires an argument." >&2; show_help ;;
+    esac
+done
+EOG
+}
+
 #------------------------------------------------------
 # options
 case $FUNC in
@@ -146,6 +164,8 @@ case $FUNC in
         func_interactive;;
     executable)
         func_executable;;
+    getopts)
+        func_getopts;;
     menu)
         func_menu;;
     *)
